version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "shikimori"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "35432:5432"
