server:
  port: 8080

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  secretKey: "secretKeyViktor"
  refresh_secret: "secretRefresh"
  allowed-origin: "http://localhost:3000"

secret: "SECRET"

services:
  user:
    url: 'http://localhost:8081'
