server:
  port: 8080

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

security:
  secret: "SECRET"
  refresh_secret: "secretRefresh"
  session-duration-minutes: 86400
  allowed-origin: "http://localhost:3000"

services:
  user:
    url: 'http://localhost:8081'

jwt:
  access_token_name: "JWT"
  refresh_token_name: "JWT_REFRESH"
